[package]
name = "part2_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
parking_lot = "0.12.1"
rayon = "1.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
